/* ═══════════════════════════════════════════════════════════════════
   HERBARZ POLSKI — rozszerzony indeks nazwisk herbowych
   Opracowano na podstawie indeksów herbarzy: Niesieckiego, Bonieckiego,
   Uruskiego i Gajla. Listy scalane z bazą HERBY po załadowaniu.
   ═══════════════════════════════════════════════════════════════════ */
const HERBOWNI2 = {
"Sas":["Baraniecki","Batycki","Bereżański","Bilczewski","Błażowski","Bojczuk","Bratkowski","Buczkowski","Bukojemski","Chodkowski","Czulewicz","Ćwikłowski","Dąbrowiecki","Dubaniowski","Dwernicki","Fedorowicz","Hołowczyc","Hołubowicz","Horbaczewski","Hrycyna","Ihnatowicz","Jasienicki","Kalinowicz","Kamionka","Kobylański","Koczerhan","Kołodnicki","Komarnicki","Kopystyński","Krasowski","Kryniecki","Krzeczkowski","Kunicki","Lachowicz","Laskowski","Lisowiecki","Litwinowicz","Lityński","Ławrowski","Łomnicki","Łopatkiewicz","Maksymowicz","Medyński","Michniowski","Monastyrski","Mszaniecki","Nehrebecki","Olchowski","Ortyński","Ostapowicz","Pasławski","Pletenicki","Płoszczański","Podwysocki","Pokutyński","Rastawiecki","Rudnicki","Rybczyński","Rychwicki","Seneczko","Skulski","Smereczański","Sołtysik","Stebnicki","Stefanowicz","Steckiewicz","Sworakowski","Szandrowski","Szeptycki","Tatomir","Tustanowski","Tyssowski","Uherecki","Uruski","Wańkowicz","Wasylkowicz","Wołczański","Wołkowicki","Zubrzycki","Żeliborski","Żukotyński"],
"Jastrzębiec":["Balcerzak","Bartochowski","Bączkowski","Bąkiewicz","Bełchowski","Będziński","Białęcki","Bieganowski","Bielawski","Bilski","Błeszyński","Bobrownicki","Boglewski","Bolechowski","Boleszczyc","Borucki","Borzewski","Bratuski","Brzechwa","Brzeziński","Budziszewski","Bujnowski","Bzowski","Charbicki","Chlewski","Chmielewski","Cieński","Ciołkowski","Czermiński","Dąbrowski","Dobiecki","Domaniewski","Domaradzki","Duninowski","Faliszewski","Gajewski","Gawroński","Gierałtowski","Glinojecki","Gołyński","Gorzeński","Grabiński","Imbram","Jachimowski","Janikowski","Jarocki","Jarząbek","Jasieński","Kalinowski","Kamocki","Kanimir","Kęsicki","Kliński","Kłobukowski","Kochański","Konecki","Krasuski","Krzesiński","Lgocki","Lisiecki","Lubiatowski","Ługowski","Łychowski","Machowski","Masłowski","Mieszkowski","Mokronowski","Mysłowski","Nagórczewski","Niemira","Niesiołowski","Nieświastowski","Olszowski","Orłowski","Pęgowski","Pieczyfortski","Pilecki","Płazowski","Pogroszewski","Przerębski","Remiszewski","Rylski","Sieklicki","Skoraczewski","Smardzewski","Solecki","Srzeniawski","Studziński","Suchodolski","Szczawiński","Ślaski","Świdziński","Trzebiński","Tworzyjański","Uchański","Wilkoszewski","Włoszczowski","Wolski","Zaleski","Zapolski","Zborzeński","Zdziechowski","Zwoliński"],
"Lubicz":["Andrzejewski","Antoszewski","Bacławski","Bagniewski","Bartkowski","Bądarzewski","Bereśniewicz","Bezdziecki","Bobiński","Boczkowski","Bolewski","Bystrzycki","Cedrowski","Chełmiński","Chmielewski","Choromański","Chrostowski","Ciołkowski","Czarnowski","Dąbrowski","Dobrzyński","Domasławski","Drozdowski","Faszczewski","Filipowicz","Gawkowski","Głodowski","Gniazdowski","Godlewski","Grądzki","Grzymkowski","Gumowski","Idzikowski","Jabłoński","Jarnutowski","Jaruzelski","Kalinowski","Kamiński","Karwowski","Kobyliński","Kołaczkowski","Kołakowski","Koskowski","Krajewski","Krasowski","Kurzątkowski","Lubowicki","Łempicki","Łopieński","Milanowski","Mokrzecki","Moczydłowski","Mroczkowski","Myszkowski","Napiórkowski","Niedziałkowski","Nieborski","Obrycki","Orzechowski","Ossowski","Ostaszewski","Pawłowski","Pieńkowski","Piotrowski","Płoński","Praski","Przeradzki","Puchalski","Radzicki","Rakowski","Romanowski","Rutkowski","Rykowski","Sierzputowski","Sokolnicki","Stawski","Stokowski","Strzałkowski","Szczodrowski","Szumowski","Tarnowski","Trętowski","Tyszka","Wądołowski","Wierzbicki","Wiszowaty","Wojsławski","Wysocki","Zalewski","Zawadzki","Zdanowski","Żbikowski"],
"Ślepowron":["Bartołd","Białoskórski","Bieńkowski","Bobrowski","Borawski","Borowy","Braciszewski","Brzumiński","Budziszewski","Bukowski","Burzyński","Chełstowski","Chrzanowski","Cieciszowski","Ciszkowski","Czarnowski","Danowski","Dąbkowski","Dobkowski","Domaszewski","Duczymiński","Dzierżanowski","Gadomski","Gąsecki","Gierałtowski","Glinka","Głodowski","Gołyński","Grabowski","Grochowski","Herman","Idzikowski","Jabłoński","Jakubowski","Janczewski","Jarnowski","Jaskłowski","Kalinowski","Karwowski","Kierznowski","Kołakowski","Kordowski","Kosiński","Kownacki","Kraszewski","Krępski","Kucharski","Kulesza","Laskowski","Leszczyński","Lipiński","Łempicki","Łopuski","Majkowski","Makowski","Mierzejewski","Mniszewski","Mościcki","Naruszewicz","Niedziałkowski","Nurzyński","Obrębski","Olszowski","Ostaszewski","Paczkowski","Piaskowski","Pieńkowski","Piotrowski","Podbielski","Popławski","Przygodzki","Radzicki","Rogowski","Rostkowski","Rowicki","Sienicki","Sikorski","Skarżyński","Sokołowski","Stypułkowski","Suchcicki","Szczepkowski","Szumski","Świderski","Trojanowski","Trzciński","Waśniewski","Wierzbicki","Wilamowski","Wołowski","Wyszomierski","Zakrzewski","Zaliwski","Zawadzki","Zdziarski","Żochowski"],
"Prus":["Bądzyński","Bielicki","Białoszewski","Bogdański","Bolimowski","Borowski","Broniewski","Brzozowski","Charłupski","Chełmoński","Cichowski","Ciechomski","Czarnocki","Dąbrowski","Dębicki","Dłużniewski","Domaradzki","Drwalewski","Franciszkowski","Gadomski","Garwaski","Gawłowski","Główczewski","Goliński","Gorzycki","Jaktorowski","Jasieński","Kapica","Karniewski","Kawiecki","Kłopotowski","Kosiński","Kossowski","Kucharski","Lipowski","Lisowski","Machnacki","Miecznikowski","Mikołajewski","Modzelewski","Nadarzyński","Nieborowski","Nowowiejski","Osiecki","Ostaszewski","Paprocki","Pilitowski","Pruski","Przanowski","Radzanowski","Rembowski","Rusiecki","Skłodowski","Skotnicki","Sokolnicki","Suski","Szczuciński","Tarnowski","Turowski","Wardęski","Wągrocki","Wilkowski","Wysokiński","Zakrzewski","Załuskowski","Zawistowski","Żbikowski","Żelski"],
"Nałęcz":["Będlewski","Białęski","Bieganowski","Bobrowski","Brodnicki","Bukowiecki","Bytkowski","Chomęcki","Czarnecki","Człopski","Dobrogostowski","Gałczyński","Gorzycki","Grabowski","Kawnicki","Kiełczewski","Kwilecki","Lubowiecki","Łagiewnicki","Łowęcki","Mierzejewski","Miłaczewski","Nowowiejski","Obrzycki","Ostrowski","Piotrkowski","Prusinowski","Przystanowski","Roznowski","Sadowski","Samborski","Sędziwój","Sławiński","Słopanowski","Sobocki","Suchorzewski","Szczaniecki","Tomicki","Wierzbiński","Wilkowski","Zajączkowski","Zberkowski","Zdzychowski","Żabicki","Żydowski"],
"Rawicz":["Bartniki","Będkowski","Białobrzeski","Bogusławski","Boguszewski","Brzeziński","Charliński","Chodowski","Ciemniewski","Czaplicki","Dąbski","Dobrzyński","Dulski","Falęcki","Gnojnicki","Goławiński","Górski","Grotowski","Jastrzębski","Kietliński","Klimontowski","Kobylnicki","Kochowski","Krasiński","Kroczewski","Latowicki","Lipski","Michałowski","Mikulski","Mokrski","Niedabylski","Ossowiński","Ożarowski","Podleski","Rakowski","Rembieszewski","Rusiecki","Sarbski","Sarnowski","Sobieszczański","Sulikowski","Trzebieński","Wichorowski","Więckowski","Wojciechowski","Zaborowski","Załęski","Zawadzki","Żelazowski"],
"Leliwa":["Baworowski","Bądzyński","Bielawski","Bieniewski","Bogatko","Broniewski","Buczacki","Chlebowski","Cieciszewski","Czapiński","Dąmbski","Dobiesławski","Drohojowski","Działyński","Gniewosz","Gostomski","Grabianka","Iwanowski","Jabłonowski","Jarosławiecki","Kamiński","Karśnicki","Kobylnicki","Krasnodębski","Krzywiński","Lasocki","Lipnicki","Łempicki","Malowski","Miłkowski","Nieborowski","Ossowski","Ostrowski","Pierzchała","Płonczyński","Pruszkowski","Ramułt","Rybiński","Sieniński","Skorupski","Sokołowski","Starzechowski","Suski","Tarnawski","Tworowski","Witowski","Zaklika","Zawadzki","Żelisławski"],
"Korczak":["Balicki","Bażanowski","Bejda","Białobrzeski","Bierecki","Bohdanowicz","Borysławski","Bożydar","Chojnacki","Czerniejowski","Derszniak","Drohojowski","Dubrawski","Dworzycki","Gostomski","Horodyjski","Hrebnicki","Iskrzycki","Jakimowicz","Kamieniecki","Kierdejowicz","Kołaczkowski","Korytko","Krasnopolski","Kunicki","Lipski","Łahodowski","Łopatecki","Malczewski","Mieleszko","Niedźwiedzki","Ohryzko","Ostafiejczyk","Pohorecki","Prochnicki","Rohoziński","Sielecki","Skorupka","Smolnicki","Strzałkowski","Werbicki","Węgleński","Wisłocki","Wołczek","Zaderewski","Zahorowski","Żabokrzycki"],
"Ostoja":["Bakowski","Będkowski","Białobłocki","Bochotnicki","Boniecki","Brochocki","Brzozowski","Cybowski","Czarnkowski","Danilewicz","Filipowski","Gadowski","Gierałtowski","Gliński","Grabowski","Jackowski","Janowski","Karsznicki","Kobylański","Kochanowski","Kraszkowski","Lgocki","Maciejowski","Miklaszewski","Mikołajewski","Miłoszewski","Mokrski","Nagórski","Niewiarowski","Ordyniec","Ostojski","Piotrowski","Przedwojewski","Raciborski","Rogaliński","Sędzimir","Siedlecki","Ścibor-Marchocki","Ścibor-Rylski","Wierzbicki","Wilkowski","Wysocki","Zabawski","Zagórski","Zawadzki"],
"Pobóg":["Bartniki","Będkowski","Bogucki","Boniecki","Byszewski","Chełmiński","Cybulski","Czarniecki","Dunin-Wolski","Działoszyński","Esmanowski","Gorczycki","Grabiński","Jackowski","Janczewski","Kisielnicki","Kołudzki","Konopka","Kossowski","Kowalewski","Krosnowski","Milewski","Nagórski","Niedzielski","Osiecki","Piaskowski","Pobudkiewicz","Podczaski","Poniatowski","Rudzki","Sokołowski","Straszewski","Suski","Świerczyński","Wilkowski","Wierzbowski","Załuski","Zawadzki","Życki"],
"Dołęga":["Bartniczek","Będzymirowski","Bielicki","Bobrowski","Boleszczyc","Bromierski","Charzyński","Chełchowski","Cywiński","Czachowski","Dobrosielski","Duczymiński","Falęcki","Filipowicz","Gawłowski","Gąsiorowski","Glinojecki","Gościcki","Gutowski","Jabłonowski","Kęsicki","Kobylnicki","Koskowski","Kowalewski","Kozicki","Kucharski","Legucki","Machcinski","Makomaski","Mierzyński","Mrokowski","Nieborski","Ośniałowski","Piwnicki","Rembieliński","Rudowski","Sikorski","Smoleński","Srebrny","Starorypiński","Winnicki","Wołowski","Załuski","Zieliński","Żmijewski"],
"Junosza":["Bąkowski","Bielawski","Bieniecki","Bogucki","Boguski","Bromierski","Brudnicki","Chełmicki","Choromański","Ciechanowski","Czerniewski","Dłużniewski","Gadomski","Gałecki","Goliński","Gostkowski","Kadłubowski","Karwowski","Kobylnicki","Kossobudzki","Kowalewski","Krępski","Lipski","Michałowski","Mostowski","Niszczycki","Ojrzanowski","Ostrowski","Pilichowski","Płoski","Radzymiński","Rakowski","Sierpski","Smoleński","Sulkowski","Szczawiński","Wilkanowski","Zaborowski","Zaleski","Żabowski"],
"Rola":["Baranowski","Bielawski","Bieniecki","Chełstowski","Chlebowski","Ciechanowski","Czerniewski","Dłutowski","Domaradzki","Gawroński","Gizycki","Goryszewski","Grabowski","Jastrzębski","Kanigowski","Kołudzki","Kowalewski","Kozicki","Kucharski","Lasocki","Lipski","Łaszewski","Mierzejewski","Modliński","Nowowiejski","Osiecki","Ośniałowski","Piwnicki","Radzymiński","Rakowski","Rościszewski","Sadowski","Sokołowski","Suski","Szczawiński","Wilkowski","Zaborowski","Zaleski","Żabowski","Żórawski"],
"Grzymała":["Baranowski","Będkowski","Białęski","Bogucki","Broniewski","Brudzewski","Bukowski","Chełmski","Chlebowski","Cielecki","Czarnecki","Domaradzki","Gawroński","Goliński","Goślinowski","Grabowski","Jabłkowski","Jarocki","Kawiecki","Kołudzki","Kosmowski","Kowalewski","Krzesiński","Lasocki","Lipski","Łaszewski","Mierzejewski","Nagórski","Nowowiejski","Olszowski","Piwnicki","Przecławski","Rakowski","Sadowski","Sokołowski","Suski","Szczawiński","Wilkowski","Zaleski","Zbierzchowski"],
"Abdank":["Abramowicz","Bardziński","Bestrzykowski","Bieganowski","Borzysławski","Celiński","Chełkowski","Cikowski","Czekanowski","Dłutowski","Gembart","Grabkowski","Hełmski","Jaskólski","Karśnicki","Kędzierzyński","Kobylański","Kołdowski","Kossakowski","Kotowiecki","Malski","Mężyk","Mikołajewski","Oszkowski","Piętka","Poniatowski","Rogaski","Sieciński","Skoczylas","Sławoszewski","Węgierski","Widawski","Wierzchowski","Zberkowski","Żarczyński"],
"Topór":["Będkowski","Białobrzeski","Bogucki","Brzeziński","Chełmski","Cikowski","Czekanowski","Gierałtowski","Gnojnicki","Jakubowski","Kamieński","Konecki","Korzeniowski","Krasowski","Krzelczycki","Lasocki","Lgocki","Marcinkowski","Morawiecki","Nawojowski","Otwinowski","Palczowski","Rychłowski","Rytwiański","Sieciechowski","Ściborowski","Tworkowski","Ujejski","Zakliczyński","Żelazowski"],
"Radwan":["Bystrzejowski","Chomentowski","Czarnowski","Dulęba","Garbowski","Głuchowski","Gruszecki","Iłżecki","Konecki","Kowieski","Kozietulski","Krępski","Lgocki","Łuszczewski","Mikułowski","Musznicki","Nieprski","Ochocki","Piekarski","Pisarzowski","Przyłuski","Rakowiecki","Sabinowski","Skarbimirski","Wielowieyski","Zdzitowiecki"],
"Jelita":["Bidziński","Brzechwa","Buczkowski","Chorzewski","Czeladziński","Doruchowski","Dzierzkowski","Gomoliński","Jelitowski","Kawęczyński","Kliczkowski","Koniecki","Krzelczycki","Łaznowski","Mniszewski","Myszkowski","Ratoszyn","Rokszycki","Sarbiewski","Siemieński","Stradomski","Wilkoszewski","Zapartowicz","Żeleński","Żelisławski"],
"Łada":["Białosuknia","Brzumieński","Bujno","Ciemierzyński","Grądzki","Kalisz","Kołaczek","Łada-Zabłocki","Miecznikowski","Mroczek","Popielarski","Rostkowski","Sępiński","Sulkowski","Wilamowski","Zambrzycki"],
"Trzaska":["Bagieński","Brzeski","Chylin","Duczymiński","Gąsiorowski","Kobyliński","Kęczewski","Łebkowski","Mieszkowski","Nartowski","Olszewski","Praski","Regulski","Rospęcki","Strzeszewski","Świerczyński","Wypyski","Żmijewski"],
"Cholewa":["Buczyński","Chamiec","Dziewanowski","Gostomski","Kłodawski","Kosmaczewski","Krzemieniewski","Niedrzwicki","Pilchowski","Płochocki","Przeciszewski","Srzedziński","Strupczewski","Wituski"],
"Ogończyk":["Bądkowski","Byszewski","Cieszkowski","Dziewczopolski","Gembart","Krobanowski","Kutnowski","Luboński","Mierucki","Niestojemski","Osiński","Pomorski","Radzikowski","Sokołowski","Stawski","Sumiński","Świerczyński","Widawski","Wolski","Żelski"],
"Odrowąż":["Będkowski","Buczkowski","Cedrowski","Chocimowski","Czelej","Dębiński","Kietliński","Konecki","Łęcki","Miłoszewski","Petrykowski","Płaskowicki","Sędziszewski","Twardowski","Wilkoszewski","Wysocki"],
"Gozdawa":["Bogucki","Bujno","Chądzyński","Czechowski","Domaniewski","Gostyński","Kaczkowski","Kowalkowski","Mierzejewski","Ossowski","Pacowski","Piwoński","Sokolnicki","Stępowski","Sulejowski","Trojanowski","Wilkowski","Żabicki"],
"Korab":["Bartoszewski","Bogusławski","Chwalęcki","Czepowski","Gaszyński","Karśnicki","Kowalski","Kraszkowski","Łaszewski","Miedźwiedzki","Poklękowski","Russocki","Sulikowski","Wierusz","Zapolski","Zdzenicki"],
"Godziemba":["Będkowski","Cieński","Dąmbski","Kurnicki","Lubrański","Malinowski","Pigłowski","Skrzetuski","Sosnowski","Stawiski","Wodziński","Zdunowski"],
"Poraj":["Będkowski","Bnin","Bużeński","Chodakowski","Jackowski","Konarzewski","Kurozwęcki","Męciński","Poddębski","Pstrokoński","Różycki","Rzepiszewski","Wężyk"],
"Łabędź":["Będkowski","Brzeziński","Dunin-Borkowski","Dunin-Karwicki","Dunin-Wąsowicz","Kroczewski","Łabęcki","Miczyński","Osmolski","Popławski","Sulgostowski","Zaborowski"],
"Łodzia":["Będlewski","Bniński","Chraplewski","Drzewiecki","Gostyński","Krzesiński","Kurnatowski","Modrzejewski","Radomicki","Rogaliński","Szołdrski","Włościejewski"],
"Nowina":["Będkowski","Chrzanowski","Cieciszewski","Dobiecki","Gawłowski","Gniewosz","Koczowski","Modliszewski","Napiórkowski","Sędzicki","Wierzchowski","Zapolski","Złotnicki"],
"Doliwa":["Będkowski","Ciświcki","Gorzycki","Kaczkowski","Miaskowski","Pierzchliński","Sepiński","Smogulecki","Starczewski","Umiński","Wyganowski"],
"Kościesza":["Bogusz","Chojecki","Dąbrowa","Gojski","Krzywicki","Prokopowicz","Siestrzewitowski","Załęski","Zwierzchowski"],
"Pomian":["Bądkowski","Chełmicki","Dziankowski","Gostkowski","Kikowski","Linowski","Mierosławski","Piwko","Rudnicki","Sadowski","Węgierski","Włocławski"],
"Szeliga":["Bystrzycki","Czyżewski","Gordziejewski","Koszkowski","Milanowski","Poniecki","Tłubicki","Zagajewski","Żelski"],
"Szreniawa":["Bratkowski","Drużyna","Gąsiorek","Kucharski","Ośmiałowski","Rupniewski","Stadnicki","Wieruszewski"],
"Świnka":["Ciechomski","Doręgowski","Kosowski","Objazda","Sławiński","Świnarski","Zajączek","Żychliński"],
"Zaremba":["Bieganowski","Cerekwicki","Gorzeński","Kawiecki","Międzychodzki","Rozdrażewski","Skoraszewski","Suchorzewski","Ulanowski"],
};
/* ── scalenie z bazą HERBY (ładowane po herby.js) ── */
if (typeof HERBY !== "undefined") {
  for (const [nazwa, lista] of Object.entries(HERBOWNI2)) {
    const h = HERBY.find(x => x.n === nazwa);
    if (!h) continue;
    for (const naz of lista) {
      const n = naz.trim();
      if (n.length > 2 && !h.fam.includes(n)) h.fam.push(n);
    }
    h.fam.sort((a, b) => a.localeCompare(b, "pl"));
  }
}
