/**
 * Katalog źródeł map — wynik inżynierii wstecznej pakietów map dla Locus Map:
 *  - onlinemapsources.xml (gist oneyoung) — Google, IGN ES, USGS, Statkart, OWM…
 *  - pakiet AnyGIS (anygis.ru/Web/Html/Locus_ru) — kategorie: miasta, OSM,
 *    satelity, topo, Genshtab/rastry, nakładki
 *  - pakiet melda.ru/locus/maps — schematy, OSM, satelity, warstwy tras
 *  - Geoportal.gov.pl — usługi WMTS/WMS PZGIK (orto, topo, NMT, działki)
 *
 * Pola:
 *  id        — unikalny identyfikator
 *  name      — nazwa wyświetlana
 *  cat       — kategoria w managerze warstw
 *  url       — szablon XYZ ({s},{z},{x},{y},{r}) lub endpoint WMS
 *  type      — "xyz" (domyślne) | "wms"
 *  wms       — parametry WMS: { layers, format, transparent }
 *  overlay   — true = nakładka (można łączyć), false = mapa bazowa
 *  opts      — opcje Leaflet (maxZoom, subdomains, tms, opacity…)
 *  key       — id dostawcy klucza API ({key} w url podmieniane z ustawień)
 *  home      — [lat, lng, z] środek zasięgu map regionalnych (test + przelot)
 *  http      — true = tylko http (może nie działać na stronie https)
 *  desc      — krótki opis
 */

const KEY_PROVIDERS = {
  thunderforest: { name: "Thunderforest", url: "https://www.thunderforest.com/pricing/" },
  owm:           { name: "OpenWeatherMap", url: "https://openweathermap.org/api" },
  mapycz:        { name: "Mapy.cz API", url: "https://developer.mapy.cz/" },
  stadia:        { name: "Stadia Maps (Stamen)", url: "https://stadiamaps.com/" },
  tracestrack:   { name: "Tracestrack", url: "https://tracestrack.com/" },
};

const MAP_SOURCES = [
  /* ─────────── OpenStreetMap ─────────── */
  { id: "osm", name: "OSM Standard", cat: "OpenStreetMap",
    url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    opts: { maxZoom: 19, attribution: "© OpenStreetMap" },
    desc: "Klasyczny styl openstreetmap.org (Mapnik)." },
  { id: "osm-hot", name: "OSM Humanitarian (HOT)", cat: "OpenStreetMap",
    url: "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
    opts: { maxZoom: 19, subdomains: "abc", attribution: "© OSM / HOT" },
    desc: "Styl humanitarny — czytelne drogi i budynki." },
  { id: "osm-fr", name: "OSM France", cat: "OpenStreetMap",
    url: "https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png",
    opts: { maxZoom: 20, subdomains: "abc", attribution: "© OSM France" },
    desc: "Francuski styl OSM, duże przybliżenie (z20)." },
  { id: "osm-de", name: "OSM Deutschland", cat: "OpenStreetMap",
    url: "https://tile.openstreetmap.de/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© OSM DE" },
    desc: "Niemiecki styl OSM." },
  { id: "cyclosm", name: "CyclOSM (rowerowa)", cat: "OpenStreetMap",
    url: "https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png",
    opts: { maxZoom: 20, subdomains: "abc", attribution: "© CyclOSM / OSM" },
    desc: "Mapa rowerowa: infrastruktura, nawierzchnie, poidła." },
  { id: "opnv", name: "ÖPNVKarte (transport publiczny)", cat: "OpenStreetMap",
    url: "https://tileserver.memomaps.de/tilegen/{z}/{x}/{y}.png",
    opts: { maxZoom: 17, attribution: "© memomaps.de / OSM" },
    desc: "Komunikacja miejska: linie, przystanki." },
  { id: "wikimedia", name: "Wikimedia Maps", cat: "OpenStreetMap",
    url: "https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}{r}.png",
    opts: { maxZoom: 19, attribution: "© Wikimedia / OSM" },
    desc: "Styl Wikipedii, wielojęzyczne etykiety." },
  { id: "carto-light", name: "Carto Positron (jasna)", cat: "OpenStreetMap",
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    opts: { maxZoom: 20, subdomains: "abcd", attribution: "© CARTO / OSM" },
    desc: "Minimalistyczne jasne tło — idealne pod nakładki." },
  { id: "carto-dark", name: "Carto Dark Matter (ciemna)", cat: "OpenStreetMap",
    url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
    opts: { maxZoom: 20, subdomains: "abcd", attribution: "© CARTO / OSM" },
    desc: "Ciemny motyw — tryb nocny." },
  { id: "carto-voyager", name: "Carto Voyager", cat: "OpenStreetMap",
    url: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png",
    opts: { maxZoom: 20, subdomains: "abcd", attribution: "© CARTO / OSM" },
    desc: "Nawigacyjny styl Carto." },

  /* ─────────── Topo / Outdoor ─────────── */
  { id: "opentopo", name: "OpenTopoMap", cat: "Topo / Outdoor",
    url: "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
    opts: { maxZoom: 17, subdomains: "abc", attribution: "© OpenTopoMap / OSM" },
    desc: "Topograficzna z poziomicami i cieniowaniem — styl „genstab-like”." },
  { id: "4umaps", name: "4UMaps (turystyczna)", cat: "Topo / Outdoor",
    url: "https://tileserver.4umaps.com/{z}/{x}/{y}.png",
    opts: { maxZoom: 15, attribution: "© 4UMaps / OSM" },
    desc: "Europejska mapa turystyczno-rowerowa z reliefem." },
  { id: "freemap-sk", name: "Freemap Slovakia Outdoor", cat: "Topo / Outdoor",
    url: "https://outdoor.tiles.freemap.sk/{z}/{x}/{y}",
    opts: { maxZoom: 19, attribution: "© Freemap.sk / OSM" },
    home: [48.95, 19.6, 9],
    desc: "Znakomita mapa turystyczna Słowacji (+ okolice)." },
  { id: "mtbmap", name: "MTBmap.cz", cat: "Topo / Outdoor", http: true,
    url: "http://tile.mtbmap.cz/mtbmap_tiles/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© mtbmap.cz / OSM" },
    home: [49.8, 15.5, 8],
    desc: "Czeska mapa MTB/turystyczna (tylko http)." },
  { id: "turistautak", name: "Turistautak.hu (Węgry)", cat: "Topo / Outdoor", http: true,
    url: "http://map.turistautak.hu/tiles/turistautak/{z}/{x}/{y}.png",
    opts: { maxZoom: 17, attribution: "© turistautak.hu" },
    home: [47.1, 19.5, 8],
    desc: "Węgierska mapa szlaków (tylko http)." },

  /* ─────────── Satelitarne ─────────── */
  { id: "esri-imagery", name: "Esri World Imagery", cat: "Satelitarne",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 19, attribution: "© Esri, Maxar" },
    desc: "Zdjęcia satelitarne Esri — świetne pokrycie świata." },
  { id: "google-sat", name: "Google Satelita", cat: "Satelitarne",
    url: "https://mt{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}",
    opts: { maxZoom: 20, subdomains: "0123", attribution: "© Google" },
    desc: "Zobrazowania satelitarne Google (endpoint z pakietów Locus)." },
  { id: "google-hybrid", name: "Google Hybryda", cat: "Satelitarne",
    url: "https://mt{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
    opts: { maxZoom: 20, subdomains: "0123", attribution: "© Google" },
    desc: "Satelita + drogi i etykiety." },
  { id: "s2cloudless", name: "Sentinel-2 Cloudless (EOX)", cat: "Satelitarne",
    url: "https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2020_3857/default/g/{z}/{y}/{x}.jpg",
    opts: { maxZoom: 14, attribution: "© EOX / Sentinel-2" },
    desc: "Bezchmurna mozaika Sentinel-2 (ESA/EOX)." },
  { id: "nasa-bluemarble", name: "NASA Blue Marble", cat: "Satelitarne",
    url: "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/BlueMarble_ShadedRelief_Bathymetry/default/GoogleMapsCompatible_Level8/{z}/{y}/{x}.jpeg",
    opts: { maxZoom: 8, attribution: "© NASA GIBS" },
    desc: "Słynne „Blue Marble” z batymetrią (do z8)." },
  { id: "nasa-viirs", name: "NASA VIIRS — zdjęcie z wczoraj", cat: "Satelitarne",
    url: "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/{d}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg",
    opts: { maxZoom: 9, attribution: "© NASA GIBS" },
    desc: "Wczorajsze zobrazowanie satelitarne całej Ziemi (do z9)." },

  /* ─────────── Google ─────────── */
  { id: "google-road", name: "Google Mapa", cat: "Google",
    url: "https://mt{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}",
    opts: { maxZoom: 20, subdomains: "0123", attribution: "© Google" },
    desc: "Standardowa mapa drogowa Google." },
  { id: "google-terrain", name: "Google Teren", cat: "Google",
    url: "https://mt{s}.google.com/vt/lyrs=p&x={x}&y={y}&z={z}",
    opts: { maxZoom: 20, subdomains: "0123", attribution: "© Google" },
    desc: "Mapa terenowa z cieniowaniem rzeźby." },

  /* ─────────── Esri / ArcGIS ─────────── */
  { id: "esri-street", name: "Esri Street Map", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 19, attribution: "© Esri" }, desc: "Drogowa mapa świata Esri." },
  { id: "esri-topo", name: "Esri World Topo", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 19, attribution: "© Esri" }, desc: "Topograficzna mapa świata Esri." },
  { id: "esri-natgeo", name: "Esri National Geographic", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 16, attribution: "© Esri / NatGeo" }, desc: "Styl atlasowy National Geographic." },
  { id: "esri-physical", name: "Esri Physical", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 8, attribution: "© Esri" }, desc: "Mapa fizyczna świata (do z8)." },
  { id: "esri-shaded", name: "Esri Shaded Relief", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 13, attribution: "© Esri" }, desc: "Czyste cieniowanie rzeźby terenu." },
  { id: "esri-terrain", name: "Esri Terrain Base", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 13, attribution: "© Esri" }, desc: "Baza terenowa (relief + wody)." },
  { id: "esri-ocean", name: "Esri Ocean", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Base/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 13, attribution: "© Esri" }, desc: "Batymetria oceanów." },
  { id: "esri-gray", name: "Esri Light Gray", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 16, attribution: "© Esri" }, desc: "Jasne szare tło pod dane." },
  { id: "esri-darkgray", name: "Esri Dark Gray", cat: "Esri / ArcGIS",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 16, attribution: "© Esri" }, desc: "Ciemne szare tło pod dane." },

  /* ─────────── Polska — Geoportal ─────────── */
  { id: "geoportal-orto", name: "Geoportal Ortofotomapa (WMTS)", cat: "Polska — Geoportal",
    url: "https://mapy.geoportal.gov.pl/wss/service/WMTS/guest/wmts/ORTO?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTOFOTOMAPA&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=EPSG:3857:{z}&TILEROW={y}&TILECOL={x}",
    opts: { maxZoom: 19, attribution: "© GUGiK / geoportal.gov.pl" },
    home: [52.2, 19.4, 6],
    desc: "Państwowa ortofotomapa Polski — bardzo wysoka rozdzielczość." },
  { id: "geoportal-orto-hd", name: "Geoportal Ortofotomapa HD (WMS)", cat: "Polska — Geoportal",
    type: "wms",
    url: "https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution",
    wms: { layers: "Raster", format: "image/jpeg", version: "1.3.0" },
    opts: { maxZoom: 21, attribution: "© GUGiK / geoportal.gov.pl" },
    home: [52.2, 19.4, 12],
    desc: "Ortofotomapa wysokiej rozdzielczości (piksel 5–10 cm) — usługa WMS HighResolution PZGiK." },
  { id: "geoportal-nmt-solo", name: "Cieniowanie ISOK — mapa samodzielna", cat: "Polska — Geoportal",
    type: "wms",
    url: "https://mapy.geoportal.gov.pl/wss/service/PZGIK/NMT/GRID1/WMS/ShadedRelief",
    wms: { layers: "Raster", format: "image/png", version: "1.3.0" },
    opts: { maxZoom: 19, attribution: "© GUGiK / ISOK" },
    home: [49.25, 19.93, 12],
    desc: "Czyste cieniowanie lidarowego NMT jako pełna mapa (biało-szara rzeźba terenu) — świetne do czytania ukształtowania, np. w Tatrach." },
  { id: "geoportal-topo", name: "Geoportal Mapa topograficzna (WMS)", cat: "Polska — Geoportal",
    type: "wms",
    url: "https://mapy.geoportal.gov.pl/wss/service/PZGIK/mapy/WMS/MapyTopograficzne",
    wms: { layers: "Raster", format: "image/png", version: "1.3.0" },
    opts: { maxZoom: 18, attribution: "© GUGiK / geoportal.gov.pl" },
    home: [52.2, 19.4, 6],
    desc: "Rastrowe mapy topograficzne PZGiK (1:10 000 – 1:100 000)." },
  { id: "geoportal-bdot", name: "Geoportal BDOT10k mobilna (WMTS)", cat: "Polska — Geoportal",
    url: "https://mapy.geoportal.gov.pl/wss/service/WMTS/guest/wmts/G2_MOBILE_500?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=G2_MOBILE_500&STYLE=default&FORMAT=image/png&TILEMATRIXSET=EPSG:3857&TILEMATRIX=EPSG:3857:{z}&TILEROW={y}&TILECOL={x}",
    opts: { maxZoom: 18, attribution: "© GUGiK / geoportal.gov.pl" },
    home: [52.2, 19.4, 6],
    desc: "Mapa z Bazy Danych Obiektów Topograficznych (styl mobilny)." },
  { id: "ump", name: "UMP-pcPL (mapa polska OSM-like)", cat: "Polska — Geoportal", http: true,
    url: "http://tiles.ump.waw.pl/ump_tiles/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© UMP-pcPL" },
    home: [52.2, 19.4, 6],
    desc: "Uzupełniająca Mapa Polski — projekt społecznościowy (tylko http)." },

  /* ─────────── Europa — mapy krajowe ─────────── */
  { id: "swisstopo", name: "Swisstopo (Szwajcaria)", cat: "Europa — mapy krajowe",
    url: "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg",
    opts: { maxZoom: 18, attribution: "© swisstopo" },
    home: [46.8, 8.2, 8],
    desc: "Legendarna szwajcarska mapa topograficzna." },
  { id: "swissimage", name: "SWISSIMAGE orto (Szwajcaria)", cat: "Europa — mapy krajowe",
    url: "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/{z}/{x}/{y}.jpeg",
    opts: { maxZoom: 19, attribution: "© swisstopo" },
    home: [46.8, 8.2, 8],
    desc: "Ortofotomapa Szwajcarii." },
  { id: "basemap-at", name: "basemap.at (Austria)", cat: "Europa — mapy krajowe",
    url: "https://mapsneu.wien.gv.at/basemap/geolandbasemap/normal/google3857/{z}/{y}/{x}.png",
    opts: { maxZoom: 19, attribution: "© basemap.at" },
    home: [47.6, 14.1, 8],
    desc: "Oficjalna mapa bazowa Austrii." },
  { id: "basemap-at-orto", name: "basemap.at Orthofoto (Austria)", cat: "Europa — mapy krajowe",
    url: "https://mapsneu.wien.gv.at/basemap/bmaporthofoto30cm/normal/google3857/{z}/{y}/{x}.jpeg",
    opts: { maxZoom: 19, attribution: "© basemap.at" },
    home: [47.6, 14.1, 8],
    desc: "Ortofotomapa Austrii 30 cm." },
  { id: "kartverket", name: "Kartverket Topo (Norwegia)", cat: "Europa — mapy krajowe",
    url: "https://cache.kartverket.no/v1/wmts/1.0.0/topo/default/webmercator/{z}/{y}/{x}.png",
    opts: { maxZoom: 18, attribution: "© Kartverket" },
    home: [61.5, 9.0, 7],
    desc: "Norweska mapa topograficzna (następca Statkart z pakietów Locus)." },
  { id: "ign-fr-plan", name: "IGN Plan v2 (Francja)", cat: "Europa — mapy krajowe",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&STYLE=normal&FORMAT=image/png&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}",
    opts: { maxZoom: 19, attribution: "© IGN France" },
    home: [46.6, 2.4, 6],
    desc: "Oficjalny plan IGN Francja (Géoplateforme)." },
  { id: "ign-fr-orto", name: "IGN Ortofoto (Francja)", cat: "Europa — mapy krajowe",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&FORMAT=image/jpeg&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}",
    opts: { maxZoom: 19, attribution: "© IGN France" },
    home: [46.6, 2.4, 6],
    desc: "Ortofotomapa Francji." },
  { id: "ign-es-base", name: "IGN Base (Hiszpania)", cat: "Europa — mapy krajowe",
    url: "https://www.ign.es/wmts/ign-base?service=WMTS&request=GetTile&version=1.0.0&layer=IGNBaseTodo&style=default&TileMatrixSet=GoogleMapsCompatible&TileMatrix={z}&TileCol={x}&TileRow={y}&format=image/jpeg",
    opts: { maxZoom: 18, attribution: "© IGN España" },
    home: [40.2, -3.7, 6],
    desc: "Mapa bazowa IGN Hiszpania (z onlinemapsources.xml)." },
  { id: "ign-es-raster", name: "IGN MTN Raster (Hiszpania)", cat: "Europa — mapy krajowe",
    url: "https://www.ign.es/wmts/mapa-raster?service=WMTS&request=GetTile&version=1.0.0&layer=MTN&style=default&TileMatrixSet=GoogleMapsCompatible&TileMatrix={z}&TileCol={x}&TileRow={y}&format=image/jpeg",
    opts: { maxZoom: 18, attribution: "© IGN España" },
    home: [40.2, -3.7, 6],
    desc: "Skanowane mapy topograficzne MTN Hiszpanii." },
  { id: "ign-es-pnoa", name: "PNOA Ortofoto (Hiszpania)", cat: "Europa — mapy krajowe",
    url: "https://www.ign.es/wmts/pnoa-ma?service=WMTS&request=GetTile&version=1.0.0&layer=OI.OrthoimageCoverage&style=default&TileMatrixSet=GoogleMapsCompatible&TileMatrix={z}&TileCol={x}&TileRow={y}&format=image/jpeg",
    opts: { maxZoom: 19, attribution: "© IGN España" },
    home: [40.2, -3.7, 6],
    desc: "Ortofotomapa PNOA Hiszpanii." },
  { id: "topplus", name: "TopPlusOpen (BKG, Europa)", cat: "Europa — mapy krajowe",
    url: "https://sgx.geodatenzentrum.de/wmts_topplus_open/tile/1.0.0/web/default/WEBMERC/{z}/{y}/{x}.png",
    opts: { maxZoom: 18, attribution: "© BKG TopPlusOpen" },
    home: [51.2, 10.4, 6],
    desc: "Zapasowa mapa topograficzna BKG — pokrywa całą Europę, bez klucza (z listy leaflet-providers)." },
  { id: "topplus-grau", name: "TopPlusOpen szara (BKG)", cat: "Europa — mapy krajowe",
    url: "https://sgx.geodatenzentrum.de/wmts_topplus_open/tile/1.0.0/web_grau/default/WEBMERC/{z}/{y}/{x}.png",
    opts: { maxZoom: 18, attribution: "© BKG TopPlusOpen" },
    home: [51.2, 10.4, 6],
    desc: "Szary wariant TopPlusOpen — idealne tło pod nakładki i POI." },
  { id: "basemap-de", name: "basemap.de (Niemcy)", cat: "Europa — mapy krajowe",
    url: "https://sgx.geodatenzentrum.de/wmts_basemapde/tile/1.0.0/de_basemapde_web_raster_farbe/default/GLOBAL_WEBMERCATOR/{z}/{y}/{x}.png",
    opts: { maxZoom: 18, attribution: "© BKG basemap.de" },
    home: [51.2, 10.4, 6],
    desc: "Oficjalna mapa bazowa Niemiec (BKG)." },

  /* ─────────── Ameryka / świat ─────────── */
  { id: "usgs-topo", name: "USGS Topo (USA)", cat: "Ameryka / świat",
    url: "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 16, attribution: "© USGS" },
    home: [39.8, -98.6, 5],
    desc: "Amerykańska mapa topograficzna (z onlinemapsources.xml)." },
  { id: "usgs-imagery", name: "USGS Imagery (USA)", cat: "Ameryka / świat",
    url: "https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 16, attribution: "© USGS" },
    home: [39.8, -98.6, 5],
    desc: "Zobrazowania lotnicze USGS." },
  { id: "usgs-imgtopo", name: "USGS Imagery+Topo (USA)", cat: "Ameryka / świat",
    url: "https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 16, attribution: "© USGS" },
    home: [39.8, -98.6, 5],
    desc: "Hybryda: zdjęcia + topografia." },

  /* ─────────── Rosja / Wschód (styl AnyGIS) ─────────── */
  { id: "wikimapia-solo", name: "Wikimapia — mapa samodzielna", cat: "Rosja / Wschód",
    combo: ["carto-light", "wikimapia"],
    url: "combo",
    opts: { maxZoom: 19, attribution: "© Wikimapia / CARTO / OSM" },
    desc: "Wikimapia jako pełna mapa: jasne tło Carto + obrysy i nazwy obiektów Wikimapii (kafelki hybrid są przezroczyste, więc samodzielny wariant to mapa zespolona)." },
  { id: "2gis", name: "2GIS", cat: "Rosja / Wschód",
    url: "https://tile2.maps.2gis.com/tiles?x={x}&y={y}&z={z}&v=1",
    opts: { maxZoom: 18, attribution: "© 2GIS" },
    home: [55.0, 82.9, 10],
    desc: "Szczegółowe plany miast Rosji i WNP (z pakietu melda)." },
  /* ─────────── Mapy historyczne (w tym rosyjskie sztabowe) ─────────── */
  { id: "nakarte-topo250", name: "Sztabowa ZSRR 1:25 000 (nakarte)", cat: "Mapy historyczne",
    url: "https://tiles.nakarte.me/topo250/{z}/{x}/{y}",
    opts: { maxZoom: 15, tms: true, attribution: "© nakarte.me" },
    home: [55.7, 37.6, 10],
    desc: "Najdokładniejsze radzieckie mapy sztabowe 1:25 000 (Genshtab, nakarte.me)." },
  { id: "nakarte-topo500", name: "Sztabowa ZSRR 1:50 000 (nakarte)", cat: "Mapy historyczne",
    url: "https://tiles.nakarte.me/topo500/{z}/{x}/{y}",
    opts: { maxZoom: 14, tms: true, attribution: "© nakarte.me" },
    home: [55.7, 37.6, 8],
    desc: "Radzieckie mapy sztabowe 1:50 000 (kategoria „Genshtab” AnyGIS)." },
  { id: "nakarte-topo1000", name: "Sztabowa ZSRR 1:100 000 (nakarte)", cat: "Mapy historyczne",
    url: "https://tiles.nakarte.me/topo1000/{z}/{x}/{y}",
    opts: { maxZoom: 13, tms: true, attribution: "© nakarte.me" },
    home: [55.7, 37.6, 8],
    desc: "Radzieckie mapy sztabowe 1:100 000." },
  { id: "marshruty", name: "Sztabowa ZSRR — Marshruty.ru", cat: "Mapy historyczne", http: true,
    url: "http://maps.marshruty.ru/ml.ashx?x={x}&y={y}&z={z}&i=1&al=1",
    opts: { maxZoom: 15, attribution: "© marshruty.ru" },
    home: [55.7, 37.6, 8],
    desc: "Mapy sztabowe z marshruty.ru (tylko http)." },
  { id: "hist-wig100k", name: "WIG 1:100 000 (Polska 1919–39)", cat: "Mapy historyczne",
    url: "https://wms.hgis.cartomatic.pl/topo/3857/wig100k/{z}/{x}/{y}.png",
    opts: { maxZoom: 15, attribution: "© HGIS cartomatic.pl / WIG" },
    home: [52.2, 21.0, 9],
    desc: "Przedwojenna mapa taktyczna Wojskowego Instytutu Geograficznego (serwer HGIS Cartomatic)." },
  { id: "hist-m25k", name: "Messtischblätter 1:25 000 (Prusy)", cat: "Mapy historyczne",
    url: "https://wms.hgis.cartomatic.pl/topo/3857/m25k/{z}/{x}/{y}.png",
    opts: { maxZoom: 15, attribution: "© HGIS cartomatic.pl" },
    home: [53.4, 14.6, 10],
    desc: "Pruskie arkusze 1:25 000 (XIX/XX w.) — zachodnia i północna Polska." },
  { id: "hist-usa-topo", name: "USA Topo — skany USGS (Esri)", cat: "Mapy historyczne",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 15, attribution: "© Esri / USGS" },
    home: [39.8, -98.6, 5],
    desc: "Zeskanowane historyczne arkusze topograficzne USGS." },
  { id: "hist-nls", name: "Wielka Brytania OS 1919–47 (NLS)", cat: "Mapy historyczne",
    url: "https://nls-{s}.tileserver.com/nls/{z}/{x}/{y}.jpg",
    opts: { maxZoom: 14, subdomains: "0123", attribution: "© National Library of Scotland" },
    home: [54.5, -2.5, 7],
    desc: "Historyczne arkusze Ordnance Survey z biblioteki NLS." },

  /* ─────────── Nakładki — szlaki ─────────── */
  { id: "wt-hiking", name: "Szlaki piesze (Waymarked)", cat: "Nakładki — szlaki", overlay: true,
    url: "https://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© Waymarked Trails" },
    desc: "Znakowane szlaki piesze całego świata." },
  { id: "wt-cycling", name: "Szlaki rowerowe (Waymarked)", cat: "Nakładki — szlaki", overlay: true,
    url: "https://tile.waymarkedtrails.org/cycling/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© Waymarked Trails" },
    desc: "Trasy rowerowe (EuroVelo, krajowe, lokalne)." },
  { id: "wt-mtb", name: "Szlaki MTB (Waymarked)", cat: "Nakładki — szlaki", overlay: true,
    url: "https://tile.waymarkedtrails.org/mtb/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© Waymarked Trails" },
    desc: "Trasy MTB." },
  { id: "wt-riding", name: "Szlaki konne (Waymarked)", cat: "Nakładki — szlaki", overlay: true,
    url: "https://tile.waymarkedtrails.org/riding/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© Waymarked Trails" },
    desc: "Szlaki jeździeckie." },
  { id: "wt-skating", name: "Trasy rolkowe (Waymarked)", cat: "Nakładki — szlaki", overlay: true,
    url: "https://tile.waymarkedtrails.org/skating/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© Waymarked Trails" },
    desc: "Trasy na rolki/wrotki." },
  { id: "wt-slopes", name: "Stoki i trasy zimowe (Waymarked)", cat: "Nakładki — szlaki", overlay: true,
    url: "https://tile.waymarkedtrails.org/slopes/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© Waymarked Trails" },
    desc: "Trasy narciarskie i wyciągi." },
  { id: "opensnowmap", name: "OpenSnowMap — trasy narciarskie", cat: "Nakładki — szlaki", overlay: true,
    url: "https://tiles.opensnowmap.org/pistes/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© opensnowmap.org" },
    desc: "Nakładka narciarska (z pakietu melda: OpenSnowMap)." },

  /* ─────────── Nakładki — transport ─────────── */
  { id: "orm-standard", name: "OpenRailwayMap — infrastruktura", cat: "Nakładki — transport", overlay: true,
    url: "https://{s}.tiles.openrailwaymap.org/standard/{z}/{x}/{y}.png",
    opts: { maxZoom: 19, subdomains: "abc", attribution: "© OpenRailwayMap" },
    desc: "Linie kolejowe, bocznice, dworce." },
  { id: "orm-maxspeed", name: "OpenRailwayMap — prędkości", cat: "Nakładki — transport", overlay: true,
    url: "https://{s}.tiles.openrailwaymap.org/maxspeed/{z}/{x}/{y}.png",
    opts: { maxZoom: 19, subdomains: "abc", attribution: "© OpenRailwayMap" },
    desc: "Prędkości szlakowe kolei." },
  { id: "orm-signals", name: "OpenRailwayMap — sygnalizacja", cat: "Nakładki — transport", overlay: true,
    url: "https://{s}.tiles.openrailwaymap.org/signals/{z}/{x}/{y}.png",
    opts: { maxZoom: 19, subdomains: "abc", attribution: "© OpenRailwayMap" },
    desc: "Semafory i sygnalizacja kolejowa." },
  { id: "openseamap", name: "OpenSeaMap — oznakowanie nawigacyjne", cat: "Nakładki — transport", overlay: true,
    url: "https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png",
    opts: { maxZoom: 18, attribution: "© OpenSeaMap" },
    desc: "Boje, latarnie, tory wodne (z onlinemapsources.xml)." },
  { id: "google-roads", name: "Google — same drogi (hybryda)", cat: "Nakładki — transport", overlay: true,
    url: "https://mt{s}.google.com/vt/lyrs=h&x={x}&y={y}&z={z}",
    opts: { maxZoom: 20, subdomains: "0123", attribution: "© Google" },
    desc: "Nakładka dróg i etykiet Google — idealna na satelitę." },
  { id: "esri-transport", name: "Esri — drogi (nakładka)", cat: "Nakładki — transport", overlay: true,
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 19, attribution: "© Esri" },
    desc: "Sieć drogowa Esri jako nakładka." },
  { id: "esri-labels", name: "Esri — granice i nazwy (nakładka)", cat: "Nakładki — transport", overlay: true,
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 19, attribution: "© Esri" },
    desc: "Granice administracyjne i nazwy miejscowości." },

  /* ─────────── Nakładki — teren i kataster ─────────── */
  { id: "esri-hillshade", name: "Cieniowanie terenu (Esri)", cat: "Nakładki — teren i kataster", overlay: true,
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
    opts: { maxZoom: 15, opacity: 0.45, attribution: "© Esri" },
    desc: "Globalny hillshade — nałóż na dowolną mapę." },
  { id: "geoportal-nmt", name: "Cieniowanie ISOK — NMT lidar (PL)", cat: "Nakładki — teren i kataster", overlay: true,
    type: "wms",
    url: "https://mapy.geoportal.gov.pl/wss/service/PZGIK/NMT/GRID1/WMS/ShadedRelief",
    wms: { layers: "Raster", format: "image/png", version: "1.3.0" },
    opts: { maxZoom: 19, opacity: 0.55, attribution: "© GUGiK / ISOK" },
    home: [52.2, 19.4, 11],
    desc: "Cieniowanie rzeźby z lidarowego NMT (projekt ISOK) — WMS 1.3.0/EPSG:3857, nałóż na dowolną mapę." },
  /* Wikimapia — kafelki hybrid z subdomeną liczoną wzorem hash = x%4 + (y%4)*4
     (i0–i15.wikimapia.org), jak w pluginie leaflet.wikimapia i pakietach
     AnyGIS/SAS.Planet. Serwery są tylko http, więc wariant „https" idzie
     przez publiczny proxy obrazków wsrv.nl (images.weserv.nl). */
  { id: "wikimapia", name: "Wikimapia — obiekty (https, zawsze działa)", cat: "Nakładki — teren i kataster",
    overlay: true, wm: "proxy",
    url: "wikimapia-hash",
    opts: { maxZoom: 19, attribution: "© Wikimapia / wsrv.nl" },
    desc: "Obrysy i nazwy obiektów Wikimapii przez proxy https wsrv.nl — działa też na stronie https (github.io). Nakładaj na Google, satelitę, OSM." },
  { id: "wikimapia-direct", name: "Wikimapia — obiekty (bezpośrednio, http)", cat: "Nakładki — teren i kataster",
    overlay: true, wm: "direct", http: true,
    url: "wikimapia-hash",
    opts: { maxZoom: 19, attribution: "© Wikimapia" },
    desc: "Bezpośrednie kafelki i0–i15.wikimapia.org (jak w Locus/AnyGIS) — szybsze, ale http: działa lokalnie i w aplikacji Android." },
  { id: "gugik-dzialki", name: "Działki ewidencyjne GUGiK (PL)", cat: "Nakładki — teren i kataster", overlay: true,
    type: "wms",
    url: "https://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow",
    wms: { layers: "dzialki,numery_dzialek", format: "image/png", transparent: true, version: "1.3.0" },
    opts: { maxZoom: 20, minZoom: 12, attribution: "© GUGiK KIEG" },
    home: [52.2, 19.4, 14],
    desc: "Granice i numery działek (widoczne od z12)." },

  /* ─────────── Pogoda — klucz OWM ─────────── */
  { id: "owm-clouds", name: "Chmury (OWM)", cat: "Pogoda (klucz API)", overlay: true, key: "owm",
    url: "https://tile.openweathermap.org/map/clouds_new/{z}/{x}/{y}.png?appid={key}",
    opts: { maxZoom: 19, attribution: "© OpenWeatherMap" },
    desc: "Zachmurzenie na żywo (z onlinemapsources.xml)." },
  { id: "owm-precip", name: "Opady (OWM)", cat: "Pogoda (klucz API)", overlay: true, key: "owm",
    url: "https://tile.openweathermap.org/map/precipitation_new/{z}/{x}/{y}.png?appid={key}",
    opts: { maxZoom: 19, attribution: "© OpenWeatherMap" },
    desc: "Radar opadów." },
  { id: "owm-wind", name: "Wiatr (OWM)", cat: "Pogoda (klucz API)", overlay: true, key: "owm",
    url: "https://tile.openweathermap.org/map/wind_new/{z}/{x}/{y}.png?appid={key}",
    opts: { maxZoom: 19, attribution: "© OpenWeatherMap" },
    desc: "Prędkość wiatru." },
  { id: "owm-temp", name: "Temperatura (OWM)", cat: "Pogoda (klucz API)", overlay: true, key: "owm",
    url: "https://tile.openweathermap.org/map/temp_new/{z}/{x}/{y}.png?appid={key}",
    opts: { maxZoom: 19, attribution: "© OpenWeatherMap" },
    desc: "Temperatura powietrza." },
  { id: "owm-pressure", name: "Ciśnienie (OWM)", cat: "Pogoda (klucz API)", overlay: true, key: "owm",
    url: "https://tile.openweathermap.org/map/pressure_new/{z}/{x}/{y}.png?appid={key}",
    opts: { maxZoom: 19, attribution: "© OpenWeatherMap" },
    desc: "Izobary ciśnienia." },

  /* ─────────── Premium — wymagają klucza ─────────── */
  { id: "tf-outdoors", name: "Thunderforest Outdoors", cat: "Premium (klucz API)", key: "thunderforest",
    url: "https://tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey={key}",
    opts: { maxZoom: 22, attribution: "© Thunderforest / OSM" },
    desc: "Świetna mapa outdoorowa (odpowiednik „Outdoors” z melda)." },
  { id: "tf-landscape", name: "Thunderforest Landscape", cat: "Premium (klucz API)", key: "thunderforest",
    url: "https://tile.thunderforest.com/landscape/{z}/{x}/{y}.png?apikey={key}",
    opts: { maxZoom: 22, attribution: "© Thunderforest / OSM" },
    desc: "Mapa krajobrazowa z reliefem." },
  { id: "tf-cycle", name: "Thunderforest OpenCycleMap", cat: "Premium (klucz API)", key: "thunderforest",
    url: "https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey={key}",
    opts: { maxZoom: 22, attribution: "© Thunderforest / OSM" },
    desc: "Klasyczna OpenCycleMap (z onlinemapsources.xml)." },
  { id: "tf-transport", name: "Thunderforest Transport", cat: "Premium (klucz API)", key: "thunderforest",
    url: "https://tile.thunderforest.com/transport/{z}/{x}/{y}.png?apikey={key}",
    opts: { maxZoom: 22, attribution: "© Thunderforest / OSM" },
    desc: "Mapa transportu publicznego." },
  { id: "mapycz-outdoor", name: "Mapy.cz Outdoor (turystyczna)", cat: "Premium (klucz API)", key: "mapycz",
    url: "https://api.mapy.cz/v1/maptiles/outdoor/256/{z}/{x}/{y}?apikey={key}",
    opts: { maxZoom: 19, attribution: "© Seznam.cz / Mapy.cz" },
    desc: "Najlepsza mapa turystyczna Czech/Słowacji/PL — znana z Locusa." },
  { id: "mapycz-winter", name: "Mapy.cz Zimowa", cat: "Premium (klucz API)", key: "mapycz",
    url: "https://api.mapy.cz/v1/maptiles/winter/256/{z}/{x}/{y}?apikey={key}",
    opts: { maxZoom: 19, attribution: "© Seznam.cz / Mapy.cz" },
    desc: "Wariant zimowy z trasami narciarskimi." },
  { id: "stadia-terrain", name: "Stamen Terrain (Stadia)", cat: "Premium (klucz API)", key: "stadia",
    url: "https://tiles.stadiamaps.com/tiles/stamen_terrain/{z}/{x}/{y}{r}.png?api_key={key}",
    opts: { maxZoom: 18, attribution: "© Stadia / Stamen / OSM" },
    desc: "Kultowy Stamen Terrain." },
  { id: "stadia-toner", name: "Stamen Toner (Stadia)", cat: "Premium (klucz API)", key: "stadia",
    url: "https://tiles.stadiamaps.com/tiles/stamen_toner/{z}/{x}/{y}{r}.png?api_key={key}",
    opts: { maxZoom: 18, attribution: "© Stadia / Stamen / OSM" },
    desc: "Czarno-biały Toner." },
  { id: "stadia-watercolor", name: "Stamen Watercolor (Stadia)", cat: "Premium (klucz API)", key: "stadia",
    url: "https://tiles.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.jpg?api_key={key}",
    opts: { maxZoom: 16, attribution: "© Stadia / Stamen / OSM" },
    desc: "Akwarelowa mapa artystyczna." },
  { id: "tracestrack-topo", name: "Tracestrack Topo", cat: "Premium (klucz API)", key: "tracestrack",
    url: "https://tile.tracestrack.com/topo__/{z}/{x}/{y}.png?key={key}",
    opts: { maxZoom: 19, attribution: "© Tracestrack / OSM" },
    desc: "Nowoczesna mapa topo (następca stylów outdoor OSM)." },
];

/* Kolejność kategorii w managerze warstw */
const CATEGORY_ORDER = [
  "Moje mapy (własne)",
  "OpenStreetMap",
  "Topo / Outdoor",
  "Satelitarne",
  "Google",
  "Esri / ArcGIS",
  "Polska — Geoportal",
  "Europa — mapy krajowe",
  "Ameryka / świat",
  "Rosja / Wschód",
  "Mapy historyczne",
  "Nakładki — szlaki",
  "Nakładki — transport",
  "Nakładki — teren i kataster",
  "Pogoda (klucz API)",
  "Premium (klucz API)",
];
